name: Unit tests + linting 
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing


jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build all Docker containers
      run: |
        docker compose -f docker-compose.yml build

    - name: Run the backend-test container (Unit Tests + Lint)
      run: |
        docker compose run backend-test
    
    - name: Run the frontend-test container (Unit Tests + Lint)
      run: |
        docker compose run frontend-test
