name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build all Docker containers
      run: |
        docker compose -f docker-compose.yml build

    - name: Run the backend-test container
      run: |
        docker compose -f docker-compose.yml up -d backend-test

    - name: Wait for the backend-test container to finish
      run: |
        docker-compose logs -f backend-test
        exit_code=$(docker wait $(docker-compose ps -q backend-test))
        if [ "$exit_code" -ne 0 ]; then
          echo "Backend test container failed with exit code $exit_code"
          exit $exit_code
        fi

    - name: Deploy
      if: success()
      run: |
        # Add your deployment commands here